import type { Metadata } from "next";
import { Inter, Island_Moments, Londrina_Solid } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter'});
const londrina = Londrina_Solid({ weight: ["100", "300", "400", "900"], subsets: ['latin'], variable: '--font-londrina' })
const island = Island_Moments({ weight: ["400"], subsets:[], variable: '--font-signature'})



export const metadata: Metadata = {
  title: "Tattoo Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${londrina.variable} ${island.variable} text-text`}>
        <Header />
        <main className="bg-main-bg">
          {children}
        </main>
      </body>
    </html>
  );
}
