import type { Metadata } from "next";
import { Inter, Island_Moments, Londrina_Solid } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const londrina = Londrina_Solid({
  weight: ["100", "300", "400", "900"],
  subsets: ["latin"],
  variable: "--font-londrina",
});
const island = Island_Moments({
  weight: ["400"],
  subsets: [],
  variable: "--font-signature",
});

export const metadata: Metadata = {
  title: "Tattoo Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${londrina.variable} ${island.variable} overflow-hidden relative min-h-[100vh] after:h-[78px] after:content-[''] after:block text-text bg-main-bg font-inter`}
      >
        <Header />
        <main className="bg-main-bg max-w-maxWidth mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
